test: src/main.rs ../test_input.in
	cargo run ../test_input.in
real: src/main.rs ../real_input.in
	cargo run ../real_input.in
test_d: src/main.rs ../test_input.in
	cargo run ../test_input.in
real_d: src/main.rs ../real_input.in
	cargo run ../real_input.in