test: main.cpp ../test_input.in
	g++ main.cpp -o main.o -DTEST && ./main.o
real: main.cpp ../real_input.in
	g++ main.cpp -o main.o -DREAL && ./main.o
test_d: main.cpp ../test_input.in
	g++ main.cpp -o main.o -DTEST -DDEBUG && ./main.o
real_d: main.cpp ../real_input.in
	g++ main.cpp -o main.o -DREAL -DDEBUG && ./main.o